secrets:
  psql-pw:
    file: /home/rizal/Documents/DokumenCILSYSupport/Draft Proposal/Kuasai.id/Kuasai
      Docker/modul/Advanced/Pertemuan 5/swarm-stack-3/psql-fake-password.txt
services:
  drupal:
    deploy:
      restart_policy:
        condition: on-failure
    image: cilsy/custom-drupal:latest
    ports:
    - 80:80/tcp
    volumes:
    - drupal-modules:/var/www/html/modules:rw
    - drupal-profiles:/var/www/html/profiles:rw
    - drupal-sites:/var/www/html/sites:rw
    - drupal-themes:/var/www/html/themes:rw
  postgres:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
    image: postgres:9.6
    secrets:
    - source: psql-pw
    volumes:
    - drupal-data:/var/lib/postgresql/data:rw
version: '3.1'
volumes:
  drupal-data: {}
  drupal-modules: {}
  drupal-profiles: {}
  drupal-sites: {}
  drupal-themes: {}

